# Generated by Django 4.1.7 on 2023-02-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitab',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='kitab',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
