# Generated by Django 4.1.7 on 2023-02-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitab', '0002_alter_kitab_price_alter_kitab_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitab',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='kitab',
            name='synapsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
