# Generated by Django 4.1.7 on 2023-02-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitab', '0003_kitab_cover_kitab_synapsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='kitab',
            name='category',
            field=models.ForeignKey(default='Other', on_delete=django.db.models.deletion.CASCADE, related_name='kitabs', to='kitab.category'),
        ),
    ]
